EXECUTABLES = searchsortc
DEBUG = -ggdb

CFLAGS = -Wall $(DEBUG)
CPPFLAGS = -Wall $(DEBUG)

all:	$(EXECUTABLES)

clean:
	rm $(EXECUTABLES) *~

searchsortc:	searchsortc.c

searchsortcpp:	searchsortcpp.cpp
